# Generated by Django 3.0.10 on 2020-09-04 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=100)),
                ('classtype', models.IntegerField(choices=[(0, 'Online'), (1, 'Offline')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField(verbose_name=datetime.datetime(2020, 9, 4, 13, 50, 37, 534174))),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=1)),
                ('email', models.EmailField(max_length=100)),
                ('state', models.IntegerField(choices=[(0, 'Schools'), (1, 'Works')], default=1)),
            ],
        ),
    ]
